# Generated by Django 4.1.3 on 2022-12-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=42)),
                ('Email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('ContactN', models.IntegerField()),
                ('course', models.CharField(max_length=42)),
                ('place', models.CharField(max_length=42)),
                ('mode', models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=42)),
                ('status', models.CharField(choices=[('Enquery', 'Enquery'), ('Normal_query', 'Normal_query'), ('Potential_query', 'Potential_query'), ('Cold_query', 'Cold_query')], max_length=42)),
                ('Registeard', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=42)),
                ('Comments', models.CharField(max_length=42)),
            ],
        ),
    ]
