# Generated by Django 4.1.3 on 2022-12-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyRegistration',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField()),
                ('Name', models.CharField(max_length=42)),
                ('PhoneNumber', models.CharField(max_length=42)),
                ('Email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('City', models.CharField(max_length=42)),
                ('course', models.CharField(max_length=42)),
                ('Total_Fee', models.CharField(max_length=42)),
                ('Fee_Paid', models.CharField(max_length=42)),
                ('Due_Ammount', models.CharField(max_length=42)),
                ('Due_Ammount_Date', models.CharField(max_length=42)),
                ('Invoice', models.CharField(max_length=42)),
                ('Paymement_Mode', models.CharField(max_length=42)),
                ('Timings', models.CharField(max_length=42)),
                ('Tax_Ammount', models.CharField(max_length=42)),
                ('Ammount', models.CharField(max_length=42)),
                ('Invoice2', models.CharField(max_length=42)),
                ('Batch_Detail', models.CharField(max_length=42)),
                ('status', models.CharField(choices=[('Enquery', 'Enquery'), ('Normal_query', 'Normal_query'), ('Potential_query', 'Potential_query'), ('Cold_query', 'Cold_query')], max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTransaction',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateTimeField()),
                ('Name', models.CharField(max_length=42)),
                ('Fee_Paid', models.CharField(max_length=42)),
                ('Bangalore_account', models.CharField(max_length=42)),
                ('PhoneNumber', models.CharField(max_length=42)),
                ('PuneAccount', models.CharField(max_length=42)),
                ('PaymentMode', models.CharField(max_length=42)),
                ('Tax', models.CharField(max_length=42)),
                ('UPI', models.CharField(max_length=42)),
            ],
        ),
    ]
