# Generated by Django 4.1.3 on 2022-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0002_alter_monthlyregistration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='monthlytransaction',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
