# Generated by Django 4.1.3 on 2022-12-03 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0003_alter_monthlyregistration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlytransaction',
            old_name='Bangalore_account',
            new_name='Payed_to_account',
        ),
        migrations.RemoveField(
            model_name='monthlytransaction',
            name='PuneAccount',
        ),
    ]
