# Generated by Django 4.1.3 on 2022-12-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0017_alter_monthlyregistration_invoice1_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Due_Ammount_Date',
            field=models.DateField(),
        ),
    ]
