# Generated by Django 4.1.3 on 2022-12-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0022_alter_monthlyregistration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyregistration',
            name='Invoice1_send',
        ),
    ]
