# Generated by Django 4.1.3 on 2022-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0028_remove_monthlyregistration_invoice1_send_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Installments_Date',
            field=models.DateTimeField(),
        ),
    ]
