# Generated by Django 4.1.3 on 2022-12-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0031_alter_monthlyregistration_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
