# Generated by Django 4.1.3 on 2022-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monthlytransaction',
            name='Date',
            field=models.DateField(),
        ),
    ]
