# Generated by Django 4.1.3 on 2022-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0004_rename_bangalore_account_monthlytransaction_payed_to_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Date',
            field=models.DateField(),
        ),
    ]
