# Generated by Django 4.1.3 on 2022-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0007_alter_monthlyregistration_due_ammount_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='City',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Pune', 'Pune')], max_length=42),
        ),
    ]
