# Generated by Django 4.1.3 on 2022-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0009_alter_monthlyregistration_batch_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='City',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Other', 'Other')], max_length=42),
        ),
    ]
