# Generated by Django 4.1.3 on 2022-12-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0010_alter_monthlyregistration_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyregistration',
            name='Timings',
        ),
        migrations.AddField(
            model_name='monthlytransaction',
            name='City',
            field=models.CharField(default=0, max_length=42),
        ),
        migrations.AddField(
            model_name='monthlytransaction',
            name='course',
            field=models.CharField(default=0, max_length=42),
        ),
    ]
