# Generated by Django 4.1.3 on 2022-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0011_remove_monthlyregistration_timings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlytransaction',
            name='City',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlytransaction',
            name='course',
            field=models.CharField(max_length=42),
        ),
    ]
