# Generated by Django 4.1.3 on 2022-12-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0013_alter_monthlytransaction_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Payment_completed', 'Payment_completed')], max_length=42),
        ),
    ]
