# Generated by Django 4.1.3 on 2022-12-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0015_alter_monthlyregistration_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyregistration',
            name='Invoice',
        ),
        migrations.RemoveField(
            model_name='monthlyregistration',
            name='Invoice2',
        ),
        migrations.AddField(
            model_name='monthlyregistration',
            name='Invoice1_send',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=42),
        ),
        migrations.AddField(
            model_name='monthlyregistration',
            name='Invoice2_send',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=42),
        ),
    ]
