# Generated by Django 4.1.3 on 2022-12-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0016_remove_monthlyregistration_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Invoice1_send',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Invoice2_send',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=42),
        ),
    ]
