# Generated by Django 4.1.3 on 2022-12-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0018_alter_monthlyregistration_due_ammount_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='monthlytransaction',
            name='Date',
            field=models.DateField(),
        ),
    ]
