# Generated by Django 4.1.3 on 2022-12-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0024_monthlyregistration_invoice1_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Invoice1_send',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=42),
        ),
    ]
