# Generated by Django 4.1.3 on 2022-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0025_alter_monthlyregistration_invoice1_send'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Ammount',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Invoice1_send',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Invoice2_send',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Paymement_Mode',
            field=models.CharField(blank=True, choices=[('CASH', 'CASH'), ('UPI', 'UPI'), ('NFET', 'NFET')], max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Tax_Ammount',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlytransaction',
            name='Tax',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlytransaction',
            name='UPI',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
