# Generated by Django 4.1.3 on 2022-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0027_alter_monthlytransaction_paymentmode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyregistration',
            name='Invoice1_send',
        ),
        migrations.RemoveField(
            model_name='monthlyregistration',
            name='Invoice2_send',
        ),
        migrations.AddField(
            model_name='monthlyregistration',
            name='Installments',
            field=models.CharField(choices=[('First installment', 'First installment'), ('Second installment', 'Second installment'), ('Third installment', 'Third installment')], default=0, max_length=42),
        ),
        migrations.AddField(
            model_name='monthlyregistration',
            name='Installments_Date',
            field=models.CharField(default=0, max_length=42),
        ),
        migrations.AddField(
            model_name='monthlyregistration',
            name='Invoice_send',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=42),
        ),
    ]
