# Generated by Django 4.1.3 on 2022-12-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeManagement', '0029_alter_monthlyregistration_installments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Due_Ammount',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Due_Ammount_Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Fee_Paid',
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Installments',
            field=models.CharField(choices=[('First installment', 'First installment'), ('Second installment', 'Second installment'), ('Third installment', 'Third installment')], max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Installments_Date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Invoice_send',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=42),
        ),
        migrations.AlterField(
            model_name='monthlyregistration',
            name='Total_Fee',
            field=models.CharField(blank=True, max_length=42),
        ),
    ]
